apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-example-cronjob
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
